/*
 * Regenerates every icon the site ships, from one source of truth: the
 * Instrument Serif "L" path below.
 *
 *   node scripts/icons.mjs
 *
 * The mark is the site's display serif — the same face as the home hero
 * sentence and the /about section headers — on the site's black, inside the
 * hairline every card carries. It replaced the old VS Code terminal tile
 * (white L + blue block cursor) when the site stopped looking like an editor.
 *
 * L_PATH is the outline of "L" from InstrumentSerif-Regular.ttf, extracted
 * once with fontTools' SVGPathPen. It's inlined as a path rather than set as
 * <text> so the favicon needs no font to render at 16px, and so a Google Fonts
 * revision can't quietly redraw the mark. To re-extract after a font update:
 *
 *   from fontTools.ttLib import TTFont
 *   from fontTools.pens.svgPathPen import SVGPathPen
 *   f = TTFont('lib/og-fonts/InstrumentSerif-Regular.ttf'); gs = f.getGlyphSet()
 *   pen = SVGPathPen(gs); gs[f.getBestCmap()[ord('L')]].draw(pen)
 *   print(pen.getCommands())
 *
 * Outputs (Next picks the app/ ones up by filename convention; manifest.ts
 * names the two in public/):
 *
 *   app/icon.svg        the tab icon — rounded tile, hairline ring
 *   app/favicon.ico     16/32/48 of the same tile, for older tabs
 *   app/apple-icon.png  180px, full-bleed: iOS applies its own squircle
 *   public/icon-192.png 192px tile, manifest `purpose: any`
 *   public/icon-512.png 512px full-bleed, manifest `purpose: maskable`
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')

const L_PATH =
  'M34 0Q19 0 19 11Q19 20 32 23L55 27Q76 31 82.5 38.0Q89 45 89 66V654Q89 675 82.5 682.0' +
  'Q76 689 55 693L32 697Q19 700 19 709Q19 720 34 720H217Q232 720 232 708Q232 699 221 697' +
  'L194 693Q173 690 166.5 682.0Q160 674 160 653V93Q160 57 180.5 41.0Q201 25 232 25' +
  'Q255 25 279.5 34.5Q304 44 324.0 70.5Q344 97 354 148L367 215Q370 228 382 228' +
  'Q396 228 394 211L382 23Q380 0 357 0Z'

/* Glyph metrics from the same font: the drawn L spans x 19–394.25 on a cap
   height of 720. Font space is y-up, so the transform below flips it. */
const GLYPH_X = 19
const GLYPH_W = 375.25
const GLYPH_CAP = 720

/*
 * Cap heights on the 64-unit square, one per surface, all chosen by looking at
 * the result rather than by formula:
 *
 *   tile     46 — big enough that the serif's hairlines survive a 16px tab
 *   apple    38 — smaller, because iOS crops the corners off a full-bleed square
 *   maskable 33 — Android can mask down to a circle 80% of the canvas; the L has
 *                 to sit inside that, so it's the most conservative of the three
 */
const CAP = { tile: 46, apple: 38, maskable: 33 }

/** The L on a 64-unit square at `cap`, centred on its own bounding box. */
function mark(cap) {
  const s = cap / GLYPH_CAP
  const x = (64 - GLYPH_W * s) / 2 - GLYPH_X * s
  const y = (64 + cap) / 2
  return `<path transform="translate(${x.toFixed(3)} ${y.toFixed(3)}) scale(${s.toFixed(6)} -${s.toFixed(6)})" d="${L_PATH}" fill="#ffffff"/>`
}

/** Rounded tile with the card hairline — for anywhere the icon shows unmasked. */
const tile = () => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <!-- Instrument Serif "L" — the site's display serif — on black, inside the
       card hairline. A path, not text, so it needs no font at 16px.
       Generated by scripts/icons.mjs; edit there, not here. -->
  <rect width="64" height="64" rx="14" fill="#000000"/>
  <rect x="0.75" y="0.75" width="62.5" height="62.5" rx="13.25" fill="none" stroke="#ffffff" stroke-opacity="0.14" stroke-width="1.5"/>
  ${mark(CAP.tile)}
</svg>
`

/** Full-bleed square — for surfaces that round the corners themselves. */
const bleed = (cap) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" fill="#000000"/>
  ${mark(cap)}
</svg>
`

/* density high enough that the 512px raster is a downscale, never an upscale. */
const png = (svg, px) =>
  sharp(Buffer.from(svg), { density: 2400 }).resize(px, px).png({ compressionLevel: 9 }).toBuffer()

/*
 * PNG-in-ICO: a 6-byte header, one 16-byte directory entry per size, then the
 * PNGs end to end. Every browser that still reads .ico understands PNG entries,
 * and it keeps this file from needing a BMP encoder.
 */
function ico(images) {
  const header = Buffer.alloc(6)
  header.writeUInt16LE(1, 2)
  header.writeUInt16LE(images.length, 4)

  const dir = Buffer.alloc(16 * images.length)
  let offset = header.length + dir.length
  images.forEach(({ px, data }, i) => {
    const o = i * 16
    dir[o] = px % 256 // 0 means 256
    dir[o + 1] = px % 256
    dir.writeUInt16LE(1, o + 4) // colour planes
    dir.writeUInt16LE(32, o + 6) // bits per pixel
    dir.writeUInt32LE(data.length, o + 8)
    dir.writeUInt32LE(offset, o + 12)
    offset += data.length
  })

  return Buffer.concat([header, dir, ...images.map((i) => i.data)])
}

async function main() {
  const tileSvg = tile()
  const write = (rel, data) => {
    fs.writeFileSync(path.join(ROOT, rel), data)
    console.log('  ' + rel)
  }

  write('app/icon.svg', tileSvg)
  write(
    'app/favicon.ico',
    ico(await Promise.all([16, 32, 48].map(async (px) => ({ px, data: await png(tileSvg, px) })))),
  )
  write('app/apple-icon.png', await png(bleed(CAP.apple), 180))
  write('public/icon-192.png', await png(tileSvg, 192))
  write('public/icon-512.png', await png(bleed(CAP.maskable), 512))
}

main()
